project:
  type: website
  output-dir: docs

website:
  title: "Newz Raviyan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
    - minty
    - custom.scss
    # mainfont: 
    # fontsize: 
    # fontcolor: 
    linkcolor: '#FFC4C4'
    # monofont: 
    #css: styles.css
    toc: true



