project:
  type: website
  output-dir: docs

website:
  title: "Newz Raviyan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: STATS330_A4.html
        text: STATS330 Statistical modelling
      - href: STATS220_A4.html
        text: STATS220 Data visualization and animation
      - href: STATS369_A2.html
        text: STATS369 on Data Cleaning and visualization
      - href: STATS369_A4.html
        text: STATS369 on Prediction using various models
      - href: STATS380_A4.html
        text: STATS380 Data cleaning

format:
  html:
    theme: 
    - minty
    - custom.scss
    # mainfont: 
    # fontsize: 
    # fontcolor: 
    linkcolor: '#FFC4C4'
    # monofont: 
    #css: styles.css
    toc: true



