<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Rudklao Raviyab">

<title>Newz Raviyan - Stats 330</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Newz Raviyan</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./STATS330_A4.html" rel="" target="">
 <span class="menu-text">STATS330 Statistical modelling</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./STATS220_A4.html" rel="" target="">
 <span class="menu-text">STATS220 Data visualization and animation</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./STATS369_A2.html" rel="" target="">
 <span class="menu-text">STATS369 on Data Cleaning and visualization</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./STATS369_A4.html" rel="" target="">
 <span class="menu-text">STATS369 on Prediction using various models</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./STATS380_A4.html" rel="" target="">
 <span class="menu-text">STATS380 Data cleaning</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#question-1" id="toc-question-1" class="nav-link active" data-scroll-target="#question-1">Question 1</a>
  <ul class="collapse">
  <li><a href="#researchers-wanted-to-use-this-dataset-to-explore-1-how-are-the-rate-of-death-or-hospitalization-due-to-heart-failure-and-the-ejection-fraction-related-and-2-is-this-relationship-the-same-for-people-taking-digoxin-and-placebo-build-a-descriptive-model-to-answer-the-question.-your-analysis-may-involve-data-exploration-model-building-model-checking-and-interpretation." id="toc-researchers-wanted-to-use-this-dataset-to-explore-1-how-are-the-rate-of-death-or-hospitalization-due-to-heart-failure-and-the-ejection-fraction-related-and-2-is-this-relationship-the-same-for-people-taking-digoxin-and-placebo-build-a-descriptive-model-to-answer-the-question.-your-analysis-may-involve-data-exploration-model-building-model-checking-and-interpretation." class="nav-link" data-scroll-target="#researchers-wanted-to-use-this-dataset-to-explore-1-how-are-the-rate-of-death-or-hospitalization-due-to-heart-failure-and-the-ejection-fraction-related-and-2-is-this-relationship-the-same-for-people-taking-digoxin-and-placebo-build-a-descriptive-model-to-answer-the-question.-your-analysis-may-involve-data-exploration-model-building-model-checking-and-interpretation.">Researchers wanted to use this dataset to explore 1) how are the rate of death or hospitalization due to heart failure and the ejection fraction related? and 2) is this relationship the same for people taking Digoxin and placebo? Build a descriptive model to answer the question. Your analysis may involve data exploration, model building, model checking and interpretation.</a></li>
  <li><a href="#plot-and-explore-data-model-selections" id="toc-plot-and-explore-data-model-selections" class="nav-link" data-scroll-target="#plot-and-explore-data-model-selections">plot and explore data, model selections</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul></li>
  <li><a href="#question-2" id="toc-question-2" class="nav-link" data-scroll-target="#question-2">Question 2</a>
  <ul class="collapse">
  <li><a href="#conduct-an-appropriate-analysis-to-access-whether-taking-digoxin-can-change-the-rate-of-death-or-hospitalization-due-to-heart-failure.-youranalysis-may-involve-data-exploration-model-building-model-checking-and-interpretation." id="toc-conduct-an-appropriate-analysis-to-access-whether-taking-digoxin-can-change-the-rate-of-death-or-hospitalization-due-to-heart-failure.-youranalysis-may-involve-data-exploration-model-building-model-checking-and-interpretation." class="nav-link" data-scroll-target="#conduct-an-appropriate-analysis-to-access-whether-taking-digoxin-can-change-the-rate-of-death-or-hospitalization-due-to-heart-failure.-youranalysis-may-involve-data-exploration-model-building-model-checking-and-interpretation.">Conduct an appropriate analysis to access whether taking digoxin can change the rate of death or hospitalization due to heart failure. Youranalysis may involve data exploration, model building, model checking and interpretation.</a></li>
  <li><a href="#conclusion-1" id="toc-conclusion-1" class="nav-link" data-scroll-target="#conclusion-1">conclusion</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Stats 330</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Rudklao Raviyab </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<p>Assignment Showcase:</p>
<p>Stats 330: Statistical Modelling</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(s20x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 's20x' was built under R version 4.3.2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mgcv)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: nlme</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>This is mgcv 1.8-42. For overview type 'help("mgcv-package")'.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:nlme':

    collapse</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MuMIn)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'MuMIn' was built under R version 4.3.2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glmtoolbox)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'glmtoolbox' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'glmtoolbox'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:MuMIn':

    QIC</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(statmod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'statmod' was built under R version 4.3.2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'MASS'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    select</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="question-1" class="level1">
<h1>Question 1</h1>
<section id="researchers-wanted-to-use-this-dataset-to-explore-1-how-are-the-rate-of-death-or-hospitalization-due-to-heart-failure-and-the-ejection-fraction-related-and-2-is-this-relationship-the-same-for-people-taking-digoxin-and-placebo-build-a-descriptive-model-to-answer-the-question.-your-analysis-may-involve-data-exploration-model-building-model-checking-and-interpretation." class="level2">
<h2 class="anchored" data-anchor-id="researchers-wanted-to-use-this-dataset-to-explore-1-how-are-the-rate-of-death-or-hospitalization-due-to-heart-failure-and-the-ejection-fraction-related-and-2-is-this-relationship-the-same-for-people-taking-digoxin-and-placebo-build-a-descriptive-model-to-answer-the-question.-your-analysis-may-involve-data-exploration-model-building-model-checking-and-interpretation.">Researchers wanted to use this dataset to explore 1) how are the rate of death or hospitalization due to heart failure and the ejection fraction related? and 2) is this relationship the same for people taking Digoxin and placebo? Build a descriptive model to answer the question. Your analysis may involve data exploration, model building, model checking and interpretation.</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>path <span class="ot">=</span> <span class="fu">file.choose</span>()</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>data.df <span class="ot">=</span> <span class="fu">read.csv</span>(path)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data.df[,<span class="fu">c</span>(<span class="st">"dwhf"</span>,<span class="st">"ejf_per"</span>,<span class="st">"trtmt1"</span>)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      dwhf           ejf_per          trtmt1      
 Min.   :0.0000   Min.   : 3.00   Min.   :0.0000  
 1st Qu.:0.0000   1st Qu.:22.00   1st Qu.:0.0000  
 Median :0.0000   Median :29.00   Median :0.0000  
 Mean   :0.3412   Mean   :28.64   Mean   :0.4983  
 3rd Qu.:1.0000   3rd Qu.:35.00   3rd Qu.:1.0000  
 Max.   :1.0000   Max.   :45.00   Max.   :1.0000  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dwhf <span class="sc">~</span> ejf_per, <span class="at">data =</span> data.df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="stats_330_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>q1<span class="ot">=</span>data.df[,<span class="fu">c</span>(<span class="st">"dwhf"</span>,<span class="st">"ejf_per"</span>,<span class="st">"trtmt1"</span>)]</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(q1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   4000 obs. of  3 variables:
 $ dwhf   : int  1 1 1 0 1 0 0 0 0 0 ...
 $ ejf_per: int  40 12 36 31 15 45 30 39 33 24 ...
 $ trtmt1 : int  0 0 0 1 0 0 1 1 0 1 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>q1<span class="sc">$</span>trtmt1<span class="ot">=</span><span class="fu">factor</span>(q1<span class="sc">$</span>trtmt1,<span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>),<span class="at">labels=</span><span class="fu">c</span>(<span class="st">"Placebo"</span>,<span class="st">"Digoxin"</span>))</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>tmp<span class="ot">=</span>q1 <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(trtmt1,ejf_per) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">prop =</span> <span class="fu">mean</span>(dwhf),<span class="at">event=</span><span class="fu">sum</span>(dwhf), <span class="at">n =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'trtmt1'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(tmp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 82 × 5
# Groups:   trtmt1 [2]
   trtmt1  ejf_per  prop event     n
   &lt;fct&gt;     &lt;int&gt; &lt;dbl&gt; &lt;int&gt; &lt;int&gt;
 1 Placebo       3 1         1     1
 2 Placebo       4 1         1     1
 3 Placebo       5 1         1     1
 4 Placebo       8 0.714     5     7
 5 Placebo       9 0.75      3     4
 6 Placebo      10 0.667    12    18
 7 Placebo      11 0.833    10    12
 8 Placebo      12 0.526    10    19
 9 Placebo      13 0.731    19    26
10 Placebo      14 0.731    19    26
# ℹ 72 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(tmp,<span class="fu">aes</span>(<span class="at">x=</span>ejf_per,<span class="at">y=</span>prop, <span class="at">color=</span>trtmt1))<span class="sc">+</span><span class="fu">geom_point</span>()<span class="sc">+</span><span class="fu">xlab</span>(<span class="st">"Ejection Fraction"</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">color=</span><span class="st">'Treatment'</span>)<span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">"Probability"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="stats_330_files/figure-html/unnamed-chunk-2-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>First we start exploring the data by looking at the summary and types of variables of our interested variables. We gathered that ejf_per is an integer while trtmt1 is the categorical data. The dwhf variable is described by R that it is an integer but infact, it is a categorical factor as it takes the value of either 0 or 1. From the raw data, we are interested in the treatment the patient actually received because patients may be allocate to placebo or Digoxin group but they may actually received different treatment from their allocated group, hence treatment1 variable was used in this analysis.</p>
<p>Then we plot a graph to see the relationship between the ejf_per and dwhf. Graph showed that the scatters are either at 0 or 1 hence, the response variable(dwhf) have a binomial distribution. Next we grouped the data into ejeculation fraction rate and treatment received. From the graph, we can see that the lower the ejection fraction, the higher probability of death with health failure. The trend exponentialy decreased as the ejection fraction increases however, both placebo and digoxin group seems to performed similary.</p>
</section>
<section id="plot-and-explore-data-model-selections" class="level2">
<h2 class="anchored" data-anchor-id="plot-and-explore-data-model-selections">plot and explore data, model selections</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>ejection.fit1 <span class="ot">=</span> <span class="fu">glm</span>(dwhf <span class="sc">~</span> ejf_per <span class="sc">+</span> trtmt1, <span class="at">data =</span> data.df, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ejection.fit1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = dwhf ~ ejf_per + trtmt1, family = "binomial", data = data.df)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  0.714408   0.119111   5.998 2.00e-09 ***
ejf_per     -0.042118   0.003933 -10.710  &lt; 2e-16 ***
trtmt1      -0.386407   0.068130  -5.672 1.41e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 5134.9  on 3999  degrees of freedom
Residual deviance: 4984.2  on 3997  degrees of freedom
AIC: 4990.2

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>After the data exploration, we are continuing with model selection. First we fitted the interested variable, the treatment patient received, and the response variable, death with hearth failure (ejection.fit1). It is the full model and from the summary, all the variables included in the model have significant relationship with the response variable due to the p-value.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>data.gam.fit <span class="ot">=</span> <span class="fu">gam</span>(dwhf <span class="sc">~</span> <span class="fu">s</span>(ejf_per) <span class="sc">+</span> trtmt1 , <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">data =</span> data.df)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data.gam.fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Family: binomial 
Link function: logit 

Formula:
dwhf ~ s(ejf_per) + trtmt1

Parametric coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -0.49050    0.04675  -10.49  &lt; 2e-16 ***
trtmt1      -0.38464    0.06820   -5.64  1.7e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Approximate significance of smooth terms:
             edf Ref.df Chi.sq p-value    
s(ejf_per) 2.351  2.965  121.5  &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

R-sq.(adj) =   0.04   Deviance explained = 3.09%
UBRE = 0.24624  Scale est. = 1         n = 4000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(data.gam.fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="stats_330_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>ejection.gam.fit2 <span class="ot">=</span> <span class="fu">glm</span>(dwhf <span class="sc">~</span> ejf_per <span class="sc">+</span> <span class="fu">I</span>(ejf_per<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> trtmt1 , <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">data =</span> data.df)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ejection.gam.fit2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = dwhf ~ ejf_per + I(ejf_per^2) + trtmt1, family = "binomial", 
    data = data.df)

Coefficients:
               Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)   1.5059883  0.3020621   4.986 6.17e-07 ***
ejf_per      -0.1058243  0.0226131  -4.680 2.87e-06 ***
I(ejf_per^2)  0.0011530  0.0004017   2.870   0.0041 ** 
trtmt1       -0.3840047  0.0682367  -5.628 1.83e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 5134.9  on 3999  degrees of freedom
Residual deviance: 4976.0  on 3996  degrees of freedom
AIC: 4984

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(ejection.gam.fit2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                     2.5 %       97.5 %
(Intercept)   0.9158869208  2.100623467
ejf_per      -0.1502557536 -0.061573623
I(ejf_per^2)  0.0003651388  0.001940529
trtmt1       -0.5179565625 -0.250438830</code></pre>
</div>
</div>
<p>Next we explore the model if there are any quadratic relationship requirement. We use gam funciton to do so (data.gam.fit). From the summary of the gam plot and the plot itself, we can see that, we can almost fit the straightline between the dotted lines but the edf is greater than 1, hence it suggests that we indeed need a quadratic term for the ejf_per variable. From the summary, the p-value for the 2nd order quadratic term on ejf_per variable is significant.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>ejection.fit2 <span class="ot">=</span> <span class="fu">glm</span>(dwhf <span class="sc">~</span> (ejf_per <span class="sc">+</span> <span class="fu">I</span>(ejf_per<span class="sc">^</span><span class="dv">2</span>)) <span class="sc">*</span> trtmt1, <span class="at">data =</span> data.df, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ejection.fit2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = dwhf ~ (ejf_per + I(ejf_per^2)) * trtmt1, family = "binomial", 
    data = data.df)

Coefficients:
                      Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)          1.7505128  0.4271430   4.098 4.16e-05 ***
ejf_per             -0.1137689  0.0320109  -3.554 0.000379 ***
I(ejf_per^2)         0.0011271  0.0005661   1.991 0.046485 *  
trtmt1              -0.8567364  0.6041512  -1.418 0.156167    
ejf_per:trtmt1       0.0133803  0.0454179   0.295 0.768297    
I(ejf_per^2):trtmt1  0.0001173  0.0008059   0.145 0.884318    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 5134.9  on 3999  degrees of freedom
Residual deviance: 4969.5  on 3994  degrees of freedom
AIC: 4981.5

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>ejection.fit3 <span class="ot">=</span> <span class="fu">glm</span>(dwhf <span class="sc">~</span> ejf_per <span class="sc">*</span> trtmt1 <span class="sc">+</span> <span class="fu">I</span>(ejf_per<span class="sc">^</span><span class="dv">2</span>), <span class="at">data =</span> data.df, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ejection.fit3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = dwhf ~ ejf_per * trtmt1 + I(ejf_per^2), family = "binomial", 
    data = data.df)

Coefficients:
                 Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)     1.7910808  0.3240355   5.527 3.25e-08 ***
ejf_per        -0.1169941  0.0231165  -5.061 4.17e-07 ***
trtmt1         -0.9381354  0.2283135  -4.109 3.97e-05 ***
I(ejf_per^2)    0.0011850  0.0004031   2.940  0.00328 ** 
ejf_per:trtmt1  0.0198905  0.0078076   2.548  0.01085 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 5134.9  on 3999  degrees of freedom
Residual deviance: 4969.5  on 3995  degrees of freedom
AIC: 4979.5

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>Lastly, we are interested in the interaction term between the ejf_per variable and the trtmt1 by fitting the ejection.fit2 model. From the summary, the p-value for the model is insignificant and we will not include any interaction term in our model and hence, our final model is ejection.gam.fit2.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">predict</span>(ejection.gam.fit2),<span class="fu">residuals</span>(ejection.gam.fit2, <span class="at">type =</span> <span class="st">"deviance"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="stats_330_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">predict</span>(ejection.gam.fit2), <span class="fu">qresiduals</span>(ejection.gam.fit2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="stats_330_files/figure-html/unnamed-chunk-6-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>); Nsim <span class="ot">=</span> <span class="fl">1e3</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>ejection.devs <span class="ot">=</span> <span class="fu">numeric</span>(Nsim); nr <span class="ot">=</span> <span class="fu">nrow</span>(data.df)</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>Nsim){</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  mos_bin <span class="ot">=</span> <span class="fu">rbinom</span>(nr, <span class="at">prob =</span> <span class="fu">predict</span>(ejection.gam.fit2, <span class="at">type =</span> <span class="st">"response"</span>), <span class="dv">1</span>)</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>  mod_i <span class="ot">=</span> <span class="fu">glm</span>(mos_bin <span class="sc">~</span> ejf_per <span class="sc">+</span> <span class="fu">I</span>(ejf_per<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> trtmt1, <span class="at">data =</span> data.df, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>  ejection.devs[i] <span class="ot">=</span> <span class="fu">deviance</span>(mod_i)</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"GOF parametric bootstrap p-value for binomial model is"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>GOF parametric bootstrap p-value for binomial model is</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span><span class="fu">mean</span>(ejection.devs <span class="sc">&lt;</span> <span class="fu">deviance</span>(ejection.gam.fit2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.485</code></pre>
</div>
</div>
<p>After our final model selection, we conduct the Goodness of fit and model assumption via randomised quantile residual plot due to the data being sparse. It showed an approximate normal distribution scatters with small fraction of scatters greater than +/- 3 on y-axis. After the assumption is satisfied, we check the goodness of fit via parametric bootstrap where the p-value showed that this model is adequate.</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>From the model selection, our final model is:</p>
<p>$ logit(\mu_i) = \beta_0 + \beta1 \times ejf_i + \beta_2 \times ejf\_per_i^2 + \beta_3 \times treatment_i $ where $ Y ~ Binomial (n_i, p_i) $</p>
<p>Where the $ logit(\mu_i) $ is the log odds of participant death or hospitalization due to heath failure. $ ejf\_ per $ is the ejection fraction (in percent) and $ \beta_3 $ is a dummy variable that take the value of 1 when treatment_i is Dignoxin and 0 when the treatment is placebo.</p>
<p>According to our research questions on how are the rate of death or hospitalization due to heart failure and the ejection fraction related. From out study, we can condluded that the relationship is quadratic and another question is whrher the relationship is the same for people taking Dignoxin and placebo. From the study, it seems to be that, if the participant received the Dignoxin treatment, the log odds of death or hospitalization is decrease by 0.38.</p>
</section>
</section>
<section id="question-2" class="level1">
<h1>Question 2</h1>
<p>Researchers were mainly interested in evaluating the causal relationships between treatment (Digoxin vs placebo) and death/hospitalization due to heart failure. They hypothesized that age, gender, ejection fraction, history of diabetes and previous digoxin use can affect the mortality and hospitalization rates. It was also hypothesized that some unknown personal characteristics can affect the treatment the patients actually received and the rate of death/hospitalization due to heart failure.</p>
<section id="conduct-an-appropriate-analysis-to-access-whether-taking-digoxin-can-change-the-rate-of-death-or-hospitalization-due-to-heart-failure.-youranalysis-may-involve-data-exploration-model-building-model-checking-and-interpretation." class="level2">
<h2 class="anchored" data-anchor-id="conduct-an-appropriate-analysis-to-access-whether-taking-digoxin-can-change-the-rate-of-death-or-hospitalization-due-to-heart-failure.-youranalysis-may-involve-data-exploration-model-building-model-checking-and-interpretation.">Conduct an appropriate analysis to access whether taking digoxin can change the rate of death or hospitalization due to heart failure. Youranalysis may involve data exploration, model building, model checking and interpretation.</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>data.df <span class="ot">=</span> <span class="fu">read.csv</span>(path)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>data.df<span class="sc">$</span>trtmt1 <span class="ot">=</span> <span class="fu">factor</span>(data.df<span class="sc">$</span>trtmt1, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Placebo"</span>, <span class="st">"Dignoxin"</span>))</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>data.df<span class="sc">$</span>trtmt <span class="ot">=</span> <span class="fu">factor</span>(data.df<span class="sc">$</span>trtmt, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Placebo"</span>, <span class="st">"Dignoxin"</span>))</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>data.df<span class="sc">$</span>sex <span class="ot">=</span> <span class="fu">factor</span>(data.df<span class="sc">$</span>sex, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Men"</span>, <span class="st">"Women"</span>))</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>data.df<span class="sc">$</span>diabetes <span class="ot">=</span> <span class="fu">factor</span>(data.df<span class="sc">$</span>diabetes, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Normal"</span>, <span class="st">"Diabetes"</span>))</span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>data.df<span class="sc">$</span>diguse <span class="ot">=</span> <span class="fu">factor</span>(data.df<span class="sc">$</span>diguse, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Yes"</span>))</span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>data.age<span class="ot">=</span>data.df <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(trtmt,age) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">prop =</span> <span class="fu">mean</span>(dwhf),<span class="at">event=</span><span class="fu">sum</span>(dwhf), <span class="at">n =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'trtmt'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data.age,<span class="fu">aes</span>(<span class="at">x=</span>age,<span class="at">y=</span>prop, <span class="at">color=</span>trtmt))<span class="sc">+</span><span class="fu">geom_point</span>()<span class="sc">+</span><span class="fu">xlab</span>(<span class="st">"age"</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">color=</span><span class="st">'Treatment'</span>)<span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">"Probability"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="stats_330_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>data.ejf<span class="ot">=</span>data.df <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(trtmt,ejf_per) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">prop =</span> <span class="fu">mean</span>(dwhf),<span class="at">event=</span><span class="fu">sum</span>(dwhf), <span class="at">n =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'trtmt'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data.ejf,<span class="fu">aes</span>(<span class="at">x=</span>ejf_per,<span class="at">y=</span>prop, <span class="at">color=</span>trtmt))<span class="sc">+</span><span class="fu">geom_point</span>()<span class="sc">+</span><span class="fu">xlab</span>(<span class="st">"ejeculation fraction"</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">color=</span><span class="st">'Treatment'</span>)<span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">"Probability"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="stats_330_files/figure-html/unnamed-chunk-7-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>data.sex<span class="ot">=</span>data.df <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(trtmt,sex) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">prop =</span> <span class="fu">mean</span>(dwhf))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'trtmt'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(data.sex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
# Groups:   trtmt [2]
  trtmt    sex    prop
  &lt;fct&gt;    &lt;fct&gt; &lt;dbl&gt;
1 Placebo  Men   0.388
2 Placebo  Women 0.371
3 Dignoxin Men   0.290
4 Dignoxin Women 0.324</code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>data.diabetes<span class="ot">=</span>data.df <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(trtmt, diabetes) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">prop =</span> <span class="fu">mean</span>(dwhf))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'trtmt'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(data.diabetes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
# Groups:   trtmt [2]
  trtmt    diabetes  prop
  &lt;fct&gt;    &lt;fct&gt;    &lt;dbl&gt;
1 Placebo  Normal   0.401
2 Placebo  Diabetes 0.340
3 Dignoxin Normal   0.296
4 Dignoxin Diabetes 0.302</code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>data.dig<span class="ot">=</span>data.df <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(trtmt, diguse) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">prop =</span> <span class="fu">mean</span>(dwhf))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'trtmt'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(data.dig)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
# Groups:   trtmt [2]
  trtmt    diguse  prop
  &lt;fct&gt;    &lt;fct&gt;  &lt;dbl&gt;
1 Placebo  No     0.330
2 Placebo  Yes    0.452
3 Dignoxin No     0.252
4 Dignoxin Yes    0.354</code></pre>
</div>
</div>
<p>First we explore the data to see the possible relationships between the explanatory variables and the outcome. It seems to be that the age in each Placebo and Dignoxin group all have similar possibility of death from heath failure. Similar to the ejection fraction but we can see that the trend is exponentially decreased as the ejection fraction increase so the lower the ejection fraction, the higher the possibility of death form heath failure. However, the placebo and Dignoxin group seems to perform similarly. As for the gender, the probability of death by heath failure seems to be similar whether the participants are male or female and whether the receive Placebo or Dignoxin. Howver, the probability of death from heath failure seems to be lower if the participants do not have diabetes and in Dignoxin group. As fro the previous use of Dignoxin, if the participants has no previous history of Dignoxin use regardless of what treatment group they are allocated to, the probability of death from heath failure seems to be lower and is even more lower then allocate to Dignoxin and similar trend in the previous use of Dignoxin.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>data.gam.fit <span class="ot">=</span> <span class="fu">gam</span>(dwhf <span class="sc">~</span> <span class="fu">s</span>(ejf_per) <span class="sc">+</span> <span class="fu">s</span>(age) <span class="sc">+</span> trtmt <span class="sc">+</span> sex <span class="sc">+</span> diabetes <span class="sc">+</span> diguse, <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">data =</span> data.df)</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data.gam.fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Family: binomial 
Link function: logit 

Formula:
dwhf ~ s(ejf_per) + s(age) + trtmt + sex + diabetes + diguse

Parametric coefficients:
                 Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)      -0.70050    0.06393 -10.958  &lt; 2e-16 ***
trtmtDignoxin    -0.39535    0.06869  -5.756 8.63e-09 ***
sexWomen          0.12739    0.08175   1.558    0.119    
diabetesDiabetes -0.08818    0.07677  -1.149    0.251    
diguseYes         0.45241    0.06871   6.584 4.58e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Approximate significance of smooth terms:
             edf Ref.df  Chi.sq p-value    
s(ejf_per) 2.410  3.039 112.816  &lt;2e-16 ***
s(age)     1.001  1.002   0.334   0.564    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

R-sq.(adj) =  0.0514   Deviance explained = 4.05%
UBRE = 0.23596  Scale est. = 1         n = 4000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(data.gam.fit, <span class="at">page =</span> <span class="dv">1</span>, <span class="at">shade=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="stats_330_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>data.fit1 <span class="ot">=</span> <span class="fu">glm</span>(dwhf <span class="sc">~</span> ejf_per <span class="sc">+</span> age <span class="sc">+</span> trtmt <span class="sc">+</span> sex <span class="sc">+</span> diabetes <span class="sc">+</span> diguse, <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">data =</span> data.df)</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data.fit1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = dwhf ~ ejf_per + age + trtmt + sex + diabetes + 
    diguse, family = "binomial", data = data.df)

Coefficients:
                  Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)       0.345830   0.236338   1.463    0.143    
ejf_per          -0.041086   0.003989 -10.300  &lt; 2e-16 ***
age               0.002022   0.003124   0.647    0.517    
trtmtDignoxin    -0.397585   0.068616  -5.794 6.86e-09 ***
sexWomen          0.132805   0.081697   1.626    0.104    
diabetesDiabetes -0.088207   0.076695  -1.150    0.250    
diguseYes         0.452137   0.068650   6.586 4.51e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 5134.9  on 3999  degrees of freedom
Residual deviance: 4934.7  on 3993  degrees of freedom
AIC: 4948.7

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>data.fit2 <span class="ot">=</span> <span class="fu">glm</span>(dwhf <span class="sc">~</span> ejf_per <span class="sc">+</span> <span class="fu">I</span>(ejf_per<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> age <span class="sc">+</span> trtmt <span class="sc">+</span> sex <span class="sc">+</span> diabetes <span class="sc">+</span> diguse, <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">data =</span> data.df)</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data.fit2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = dwhf ~ ejf_per + I(ejf_per^2) + age + trtmt + sex + 
    diabetes + diguse, family = "binomial", data = data.df)

Coefficients:
                   Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)       1.1352313  0.3702836   3.066  0.00217 ** 
ejf_per          -0.1032478  0.0227482  -4.539 5.66e-06 ***
I(ejf_per^2)      0.0011259  0.0004044   2.784  0.00537 ** 
age               0.0017564  0.0031281   0.561  0.57447    
trtmtDignoxin    -0.3944491  0.0687194  -5.740 9.47e-09 ***
sexWomen          0.1259355  0.0817674   1.540  0.12352    
diabetesDiabetes -0.0879966  0.0768024  -1.146  0.25190    
diguseYes         0.4525657  0.0687472   6.583 4.61e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 5134.9  on 3999  degrees of freedom
Residual deviance: 4927.0  on 3992  degrees of freedom
AIC: 4943

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(data.fit1, data.fit2, <span class="at">test =</span> <span class="st">"Chisq"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model 1: dwhf ~ ejf_per + age + trtmt + sex + diabetes + diguse
Model 2: dwhf ~ ejf_per + I(ejf_per^2) + age + trtmt + sex + diabetes + 
    diguse
  Resid. Df Resid. Dev Df Deviance Pr(&gt;Chi)   
1      3993     4934.7                        
2      3992     4927.0  1   7.7318 0.005426 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>data.fit3 <span class="ot">=</span> <span class="fu">glm</span>(dwhf <span class="sc">~</span> (ejf_per <span class="sc">+</span> <span class="fu">I</span>(ejf_per<span class="sc">^</span><span class="dv">2</span>))<span class="sc">*</span>trtmt <span class="sc">+</span> age <span class="sc">+</span> trtmt <span class="sc">+</span> sex <span class="sc">+</span> diabetes<span class="sc">*</span>trtmt <span class="sc">+</span> diguse, <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">data =</span> data.df)</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data.fit3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = dwhf ~ (ejf_per + I(ejf_per^2)) * trtmt + age + 
    trtmt + sex + diabetes * trtmt + diguse, family = "binomial", 
    data = data.df)

Coefficients:
                                 Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)                     1.3010627  0.4771601   2.727  0.00640 ** 
ejf_per                        -0.1025636  0.0318672  -3.218  0.00129 ** 
I(ejf_per^2)                    0.0009627  0.0005647   1.705  0.08822 .  
trtmtDignoxin                  -0.7097292  0.6079229  -1.167  0.24302    
age                             0.0016497  0.0031311   0.527  0.59829    
sexWomen                        0.1300224  0.0819190   1.587  0.11247    
diabetesDiabetes               -0.2334890  0.1071522  -2.179  0.02933 *  
diguseYes                       0.4534227  0.0688964   6.581 4.67e-11 ***
ejf_per:trtmtDignoxin          -0.0035875  0.0456365  -0.079  0.93734    
I(ejf_per^2):trtmtDignoxin      0.0003883  0.0008103   0.479  0.63173    
trtmtDignoxin:diabetesDiabetes  0.3035428  0.1535482   1.977  0.04806 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 5134.9  on 3999  degrees of freedom
Residual deviance: 4917.4  on 3989  degrees of freedom
AIC: 4939.4

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">na.action =</span> <span class="st">"na.fail"</span>)</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>all.fits <span class="ot">=</span> <span class="fu">dredge</span>(data.fit3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Fixed term is "(Intercept)"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(all.fits)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Global model call: glm(formula = dwhf ~ (ejf_per + I(ejf_per^2)) * trtmt + age + 
    trtmt + sex + diabetes * trtmt + diguse, family = "binomial", 
    data = data.df)
---
Model selection table 
    (Int) dbt dgs ejf_per ejf_per^2 sex trt dbt:trt ejf_per:trt
767 1.433   +   + -0.1047 0.0009995   +   +       +            
511 1.543   +   + -0.1134 0.0011570   +   +       +           +
735 1.453   +   + -0.1049 0.0010210       +       +            
479 1.560   +   + -0.1135 0.0011750       +       +           +
637 1.378       + -0.1049 0.0009994   +   +                    
381 1.489       + -0.1138 0.0011600   +   +                   +
    I(ejf_per^2):trt df    logLik   AICc delta weight
767                +  9 -2458.852 4935.7  0.00  0.227
511                   9 -2458.961 4936.0  0.22  0.204
735                +  8 -2460.118 4936.3  0.52  0.175
479                   8 -2460.210 4936.5  0.71  0.159
637                +  7 -2461.469 4937.0  1.22  0.124
381                   7 -2461.577 4937.2  1.43  0.111
Models ranked by AICc(x) </code></pre>
</div>
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>model.fit1 <span class="ot">=</span> <span class="fu">get.models</span>(all.fits, <span class="dv">1</span>)[[<span class="dv">1</span>]]</span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.fit1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = dwhf ~ diabetes + diguse + ejf_per + I(ejf_per^2) + 
    sex + trtmt + diabetes:trtmt + I(ejf_per^2):trtmt + 1, family = "binomial", 
    data = data.df)

Coefficients:
                                 Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)                     1.4334848  0.3144973   4.558 5.16e-06 ***
diabetesDiabetes               -0.2340189  0.1071553  -2.184   0.0290 *  
diguseYes                       0.4521039  0.0688426   6.567 5.13e-11 ***
ejf_per                        -0.1046623  0.0228043  -4.590 4.44e-06 ***
I(ejf_per^2)                    0.0009995  0.0004095   2.441   0.0147 *  
sexWomen                        0.1306861  0.0818843   1.596   0.1105    
trtmtDignoxin                  -0.7568879  0.1435191  -5.274 1.34e-07 ***
diabetesDiabetes:trtmtDignoxin  0.3050129  0.1535179   1.987   0.0469 *  
I(ejf_per^2):trtmtDignoxin      0.0003255  0.0001395   2.334   0.0196 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 5134.9  on 3999  degrees of freedom
Residual deviance: 4917.7  on 3991  degrees of freedom
AIC: 4935.7

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>model.fit2 <span class="ot">=</span> <span class="fu">get.models</span>(all.fits, <span class="dv">2</span>)[[<span class="dv">1</span>]]</span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.fit2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = dwhf ~ diabetes + diguse + ejf_per + I(ejf_per^2) + 
    sex + trtmt + diabetes:trtmt + ejf_per:trtmt + 1, family = "binomial", 
    data = data.df)

Coefficients:
                                 Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)                     1.5427863  0.3282945   4.699 2.61e-06 ***
diabetesDiabetes               -0.2340005  0.1071897  -2.183   0.0290 *  
diguseYes                       0.4517607  0.0688438   6.562 5.31e-11 ***
ejf_per                        -0.1134032  0.0232166  -4.885 1.04e-06 ***
I(ejf_per^2)                    0.0011574  0.0004053   2.855   0.0043 ** 
sexWomen                        0.1297966  0.0818695   1.585   0.1129    
trtmtDignoxin                  -0.9798958  0.2331599  -4.203 2.64e-05 ***
diabetesDiabetes:trtmtDignoxin  0.3050824  0.1535162   1.987   0.0469 *  
ejf_per:trtmtDignoxin           0.0179671  0.0078644   2.285   0.0223 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 5134.9  on 3999  degrees of freedom
Residual deviance: 4917.9  on 3991  degrees of freedom
AIC: 4935.9

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>model.fit3 <span class="ot">=</span> <span class="fu">get.models</span>(all.fits, <span class="dv">3</span>)[[<span class="dv">1</span>]]</span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.fit3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = dwhf ~ diabetes + diguse + ejf_per + I(ejf_per^2) + 
    trtmt + diabetes:trtmt + I(ejf_per^2):trtmt + 1, family = "binomial", 
    data = data.df)

Coefficients:
                                 Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)                     1.4529743  0.3141386   4.625 3.74e-06 ***
diabetesDiabetes               -0.2331058  0.1070943  -2.177   0.0295 *  
diguseYes                       0.4530750  0.0688169   6.584 4.59e-11 ***
ejf_per                        -0.1049479  0.0227934  -4.604 4.14e-06 ***
I(ejf_per^2)                    0.0010211  0.0004091   2.496   0.0126 *  
trtmtDignoxin                  -0.7532032  0.1434285  -5.251 1.51e-07 ***
diabetesDiabetes:trtmtDignoxin  0.3086010  0.1534389   2.011   0.0443 *  
I(ejf_per^2):trtmtDignoxin      0.0003182  0.0001393   2.283   0.0224 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 5134.9  on 3999  degrees of freedom
Residual deviance: 4920.2  on 3992  degrees of freedom
AIC: 4936.2

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>model.fit4 <span class="ot">=</span> <span class="fu">get.models</span>(all.fits, <span class="dv">4</span>)[[<span class="dv">1</span>]]</span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.fit4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = dwhf ~ diabetes + diguse + ejf_per + I(ejf_per^2) + 
    trtmt + diabetes:trtmt + ejf_per:trtmt + 1, family = "binomial", 
    data = data.df)

Coefficients:
                                Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)                     1.560287   0.327941   4.758 1.96e-06 ***
diabetesDiabetes               -0.233097   0.107130  -2.176  0.02957 *  
diguseYes                       0.452708   0.068819   6.578 4.76e-11 ***
ejf_per                        -0.113513   0.023203  -4.892 9.98e-07 ***
I(ejf_per^2)                    0.001175   0.000405   2.902  0.00371 ** 
trtmtDignoxin                  -0.972432   0.232999  -4.174 3.00e-05 ***
diabetesDiabetes:trtmtDignoxin  0.308636   0.153438   2.011  0.04428 *  
ejf_per:trtmtDignoxin           0.017607   0.007857   2.241  0.02504 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 5134.9  on 3999  degrees of freedom
Residual deviance: 4920.4  on 3992  degrees of freedom
AIC: 4936.4

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>model.fit5 <span class="ot">=</span> <span class="fu">get.models</span>(all.fits, <span class="dv">5</span>)[[<span class="dv">1</span>]]</span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.fit5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = dwhf ~ diguse + ejf_per + I(ejf_per^2) + sex + 
    trtmt + I(ejf_per^2):trtmt + 1, family = "binomial", data = data.df)

Coefficients:
                             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)                 1.3775741  0.3132504   4.398 1.09e-05 ***
diguseYes                   0.4512205  0.0687287   6.565 5.19e-11 ***
ejf_per                    -0.1049141  0.0227959  -4.602 4.18e-06 ***
I(ejf_per^2)                0.0009994  0.0004093   2.441   0.0146 *  
sexWomen                    0.1311644  0.0818242   1.603   0.1089    
trtmtDignoxin              -0.6780705  0.1375817  -4.928 8.29e-07 ***
I(ejf_per^2):trtmtDignoxin  0.0003313  0.0001394   2.377   0.0175 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 5134.9  on 3999  degrees of freedom
Residual deviance: 4922.9  on 3993  degrees of freedom
AIC: 4936.9

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model.fit4, data.fit3, <span class="at">test =</span> <span class="st">"Chisq"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model 1: dwhf ~ diabetes + diguse + ejf_per + I(ejf_per^2) + trtmt + diabetes:trtmt + 
    ejf_per:trtmt + 1
Model 2: dwhf ~ (ejf_per + I(ejf_per^2)) * trtmt + age + trtmt + sex + 
    diabetes * trtmt + diguse
  Resid. Df Resid. Dev Df Deviance Pr(&gt;Chi)
1      3992     4920.4                     
2      3989     4917.4  3   2.9996   0.3917</code></pre>
</div>
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data.fit3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = dwhf ~ (ejf_per + I(ejf_per^2)) * trtmt + age + 
    trtmt + sex + diabetes * trtmt + diguse, family = "binomial", 
    data = data.df)

Coefficients:
                                 Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)                     1.3010627  0.4771601   2.727  0.00640 ** 
ejf_per                        -0.1025636  0.0318672  -3.218  0.00129 ** 
I(ejf_per^2)                    0.0009627  0.0005647   1.705  0.08822 .  
trtmtDignoxin                  -0.7097292  0.6079229  -1.167  0.24302    
age                             0.0016497  0.0031311   0.527  0.59829    
sexWomen                        0.1300224  0.0819190   1.587  0.11247    
diabetesDiabetes               -0.2334890  0.1071522  -2.179  0.02933 *  
diguseYes                       0.4534227  0.0688964   6.581 4.67e-11 ***
ejf_per:trtmtDignoxin          -0.0035875  0.0456365  -0.079  0.93734    
I(ejf_per^2):trtmtDignoxin      0.0003883  0.0008103   0.479  0.63173    
trtmtDignoxin:diabetesDiabetes  0.3035428  0.1535482   1.977  0.04806 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 5134.9  on 3999  degrees of freedom
Residual deviance: 4917.4  on 3989  degrees of freedom
AIC: 4939.4

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.fit4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = dwhf ~ diabetes + diguse + ejf_per + I(ejf_per^2) + 
    trtmt + diabetes:trtmt + ejf_per:trtmt + 1, family = "binomial", 
    data = data.df)

Coefficients:
                                Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)                     1.560287   0.327941   4.758 1.96e-06 ***
diabetesDiabetes               -0.233097   0.107130  -2.176  0.02957 *  
diguseYes                       0.452708   0.068819   6.578 4.76e-11 ***
ejf_per                        -0.113513   0.023203  -4.892 9.98e-07 ***
I(ejf_per^2)                    0.001175   0.000405   2.902  0.00371 ** 
trtmtDignoxin                  -0.972432   0.232999  -4.174 3.00e-05 ***
diabetesDiabetes:trtmtDignoxin  0.308636   0.153438   2.011  0.04428 *  
ejf_per:trtmtDignoxin           0.017607   0.007857   2.241  0.02504 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 5134.9  on 3999  degrees of freedom
Residual deviance: 4920.4  on 3992  degrees of freedom
AIC: 4936.4

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a>predictions <span class="ot">=</span> <span class="fu">predict</span>(model.fit4, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb102-3"><a href="#cb102-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb102-4"><a href="#cb102-4" aria-hidden="true" tabindex="-1"></a>Nsim <span class="ot">=</span> <span class="fl">1e4</span></span>
<span id="cb102-5"><a href="#cb102-5" aria-hidden="true" tabindex="-1"></a>nb.devs <span class="ot">=</span> <span class="fu">numeric</span>(Nsim); nr <span class="ot">=</span> <span class="fu">nrow</span>(data.df)</span>
<span id="cb102-6"><a href="#cb102-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>Nsim){</span>
<span id="cb102-7"><a href="#cb102-7" aria-hidden="true" tabindex="-1"></a>  out <span class="ot">=</span> <span class="fu">rbinom</span>(nr, <span class="at">prob =</span> <span class="fu">predict</span>(model.fit4, <span class="at">type =</span> <span class="st">"response"</span>), <span class="dv">1</span>)</span>
<span id="cb102-8"><a href="#cb102-8" aria-hidden="true" tabindex="-1"></a>  data.df<span class="sc">$</span>out <span class="ot">=</span> out</span>
<span id="cb102-9"><a href="#cb102-9" aria-hidden="true" tabindex="-1"></a>  mod_i <span class="ot">=</span> <span class="fu">glm</span>(out <span class="sc">~</span> diabetes <span class="sc">+</span> diguse <span class="sc">+</span> ejf_per <span class="sc">+</span> <span class="fu">I</span>(ejf_per<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb102-10"><a href="#cb102-10" aria-hidden="true" tabindex="-1"></a>    trtmt <span class="sc">+</span> diabetes<span class="sc">*</span>trtmt <span class="sc">+</span> ejf_per<span class="sc">*</span>trtmt <span class="sc">+</span> <span class="dv">1</span>, <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">data =</span> data.df)</span>
<span id="cb102-11"><a href="#cb102-11" aria-hidden="true" tabindex="-1"></a>  nb.devs[i] <span class="ot">=</span> <span class="fu">deviance</span>(mod_i)</span>
<span id="cb102-12"><a href="#cb102-12" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb102-13"><a href="#cb102-13" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"GOF parametric bootstrap p=value for the model is "</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>GOF parametric bootstrap p=value for the model is </code></pre>
</div>
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">mean</span>(nb.devs <span class="sc">&lt;</span> <span class="fu">deviance</span>(model.fit4))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.441</code></pre>
</div>
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">predict</span>(model.fit4), <span class="fu">qresiduals</span>(model.fit4))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="stats_330_files/figure-html/unnamed-chunk-8-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>After we explore the possible relationships with the explanatory variables, we are interested to see if there are any quadratic relationships. From the gam plot(data.gam.fit), we can see that the edf of ejf_per is 2.4 while age is 1 so we need a quadratic term for ejf_per variable. We fitted the model with quadratic term (data.fit2) Comparing the AIC score between the the model without the quadratic term (data.fit1), we can see that the AIC score is smaller when there is a quadratic term for ejf_per variable.</p>
<p>Next we are interested in whether there are interaction terms between different variables. From the data exploration, we can see that there are possible interactions between treatment with ejf_per, Diabetes and previous Dignoxin use. From the dredge function, we tried to find the best model according to the AIC scores, we selected the best 5 models and evaluted the p-values of each variables selected by the dredge function. We decided to select model 479 which is the 4th best model (model.fit4) based on the data exploration that the treatment group and ejection fraction seems to have interaction. There is a better model that included the mentioned interaction but it also included sex which from the p-value, it seems to have insignificant relationship with the dwhf so we decided to pick this model.</p>
<p>we conducted the model assumption and goodness of fit via randomised quantile residual plots as the data is sparse and parametric bootstrap. The randomised quantile residule showed an approximately normal distribution with small fraction of scatters over +/- 3 magnitude in y-axis. The p-value generated from parametric bootstrap suggests that there is no evidence model inadequate.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'emmeans' was built under R version 4.3.2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.fit4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = dwhf ~ diabetes + diguse + ejf_per + I(ejf_per^2) + 
    trtmt + diabetes:trtmt + ejf_per:trtmt + 1, family = "binomial", 
    data = data.df)

Coefficients:
                                Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)                     1.560287   0.327941   4.758 1.96e-06 ***
diabetesDiabetes               -0.233097   0.107130  -2.176  0.02957 *  
diguseYes                       0.452708   0.068819   6.578 4.76e-11 ***
ejf_per                        -0.113513   0.023203  -4.892 9.98e-07 ***
I(ejf_per^2)                    0.001175   0.000405   2.902  0.00371 ** 
trtmtDignoxin                  -0.972432   0.232999  -4.174 3.00e-05 ***
diabetesDiabetes:trtmtDignoxin  0.308636   0.153438   2.011  0.04428 *  
ejf_per:trtmtDignoxin           0.017607   0.007857   2.241  0.02504 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 5134.9  on 3999  degrees of freedom
Residual deviance: 4920.4  on 3992  degrees of freedom
AIC: 4936.4

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a>odds <span class="ot">=</span> <span class="fu">exp</span>(model.fit4<span class="sc">$</span>coefficients)</span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a>odds</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   (Intercept)               diabetesDiabetes 
                     4.7601860                      0.7920771 
                     diguseYes                        ejf_per 
                     1.5725650                      0.8926928 
                  I(ejf_per^2)                  trtmtDignoxin 
                     1.0011760                      0.3781623 
diabetesDiabetes:trtmtDignoxin          ejf_per:trtmtDignoxin 
                     1.3615664                      1.0177631 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a>ORs<span class="ot">=</span><span class="fu">exp</span>(<span class="fu">confint</span>((model.fit4)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a>ORs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                   2.5 %    97.5 %
(Intercept)                    2.5096847 9.0827328
diabetesDiabetes               0.6413363 0.9762045
diguseYes                      1.3742534 1.7998615
ejf_per                        0.8528941 0.9341440
I(ejf_per^2)                   1.0003811 1.0019711
trtmtDignoxin                  0.2393143 0.5966466
diabetesDiabetes:trtmtDignoxin 1.0077939 1.8392937
ejf_per:trtmtDignoxin          1.0022114 1.0335682</code></pre>
</div>
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a>compare1 <span class="ot">=</span> <span class="fu">emmeans</span>(model.fit4, pairwise  <span class="sc">~</span> diabetes <span class="sc">*</span> trtmt, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb117-2"><a href="#cb117-2" aria-hidden="true" tabindex="-1"></a>compare1<span class="sc">$</span>contrasts</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast                             odds.ratio    SE  df null z.ratio p.value
 Normal Placebo / Diabetes Placebo         1.263 0.135 Inf    1   2.176  0.1300
 Normal Placebo / Normal Dignoxin          1.597 0.130 Inf    1   5.767  &lt;.0001
 Normal Placebo / Diabetes Dignoxin        1.481 0.160 Inf    1   3.644  0.0015
 Diabetes Placebo / Normal Dignoxin        1.265 0.138 Inf    1   2.148  0.1381
 Diabetes Placebo / Diabetes Dignoxin      1.173 0.153 Inf    1   1.224  0.6115
 Normal Dignoxin / Diabetes Dignoxin       0.927 0.102 Inf    1  -0.688  0.9019

Results are averaged over the levels of: diguse 
P value adjustment: tukey method for comparing a family of 4 estimates 
Tests are performed on the log odds ratio scale </code></pre>
</div>
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a>tmp <span class="ot">=</span> <span class="fu">summary</span>(compare1<span class="sc">$</span>contrasts)</span>
<span id="cb119-2"><a href="#cb119-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb119-3"><a href="#cb119-3" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">=</span> <span class="fu">emmip</span> (model.fit4, trtmt <span class="sc">~</span> ejf_per <span class="sc">*</span>diabetes, </span>
<span id="cb119-4"><a href="#cb119-4" aria-hidden="true" tabindex="-1"></a><span class="at">at =</span> <span class="fu">list</span>(<span class="at">ejf_per =</span> <span class="dv">3</span><span class="sc">:</span><span class="dv">45</span>, <span class="at">diabetes =</span> <span class="st">"Normal"</span>), <span class="at">type =</span> <span class="st">"response"</span>, <span class="at">CIs =</span> <span class="cn">TRUE</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">"Ejection Fraction"</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">"Probability"</span>)<span class="sc">+</span></span>
<span id="cb119-5"><a href="#cb119-5" aria-hidden="true" tabindex="-1"></a><span class="fu">scale_x_discrete</span>(<span class="at">breaks =</span> <span class="fu">paste</span>(<span class="dv">3</span><span class="sc">:</span><span class="dv">45</span>, <span class="st">"Normal"</span>)[<span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">3</span>, <span class="at">to =</span> <span class="dv">45</span>, <span class="at">by=</span><span class="dv">5</span>)], <span class="at">labels =</span> <span class="fu">c</span>(<span class="dv">3</span><span class="sc">:</span><span class="dv">45</span>)</span>
<span id="cb119-6"><a href="#cb119-6" aria-hidden="true" tabindex="-1"></a>[<span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">3</span>, <span class="at">to=</span><span class="dv">45</span>, <span class="at">by =</span> <span class="dv">5</span>)]) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">color =</span> <span class="st">'treatment'</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"No Diabetes"</span>)</span>
<span id="cb119-7"><a href="#cb119-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb119-8"><a href="#cb119-8" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">=</span> <span class="fu">emmip</span> (model.fit4, trtmt <span class="sc">~</span> ejf_per <span class="sc">*</span>diabetes, </span>
<span id="cb119-9"><a href="#cb119-9" aria-hidden="true" tabindex="-1"></a><span class="at">at =</span> <span class="fu">list</span>(<span class="at">ejf_per =</span> <span class="dv">3</span><span class="sc">:</span><span class="dv">45</span>, <span class="at">diabetes =</span> <span class="st">"Diabetes"</span>), <span class="at">type =</span> <span class="st">"response"</span>, <span class="at">CIs =</span> <span class="cn">TRUE</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">"Ejection Fraction"</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">"Probability"</span>)<span class="sc">+</span></span>
<span id="cb119-10"><a href="#cb119-10" aria-hidden="true" tabindex="-1"></a><span class="fu">scale_x_discrete</span>(<span class="at">breaks =</span> <span class="fu">paste</span>(<span class="dv">3</span><span class="sc">:</span><span class="dv">45</span>, <span class="st">"Diabetes"</span>)[<span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">3</span>, <span class="at">to =</span> <span class="dv">45</span>, <span class="at">by=</span><span class="dv">5</span>)], <span class="at">labels =</span> <span class="fu">c</span>(<span class="dv">3</span><span class="sc">:</span><span class="dv">45</span>)</span>
<span id="cb119-11"><a href="#cb119-11" aria-hidden="true" tabindex="-1"></a>[<span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">3</span>, <span class="at">to=</span><span class="dv">45</span>, <span class="at">by =</span> <span class="dv">5</span>)]) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">color =</span> <span class="st">'Treatment'</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"Diabetes"</span>)</span>
<span id="cb119-12"><a href="#cb119-12" aria-hidden="true" tabindex="-1"></a>ggpubr<span class="sc">::</span><span class="fu">ggarrange</span>(p1,p2, <span class="at">common.legend =</span> <span class="cn">TRUE</span>, <span class="at">legend =</span> <span class="st">"bottom"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="stats_330_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="conclusion-1" class="level2">
<h2 class="anchored" data-anchor-id="conclusion-1">conclusion</h2>
<p>our final model is as following:</p>
<p>$ logit(\mu_i) = \beta_0 + \beta_1 \times diabetes_i + \beta_2 \times diguse_i + \beta_3 \times ejf\_per_i + \beta_4 \times ejf\_per_i^2 + \beta_4 \times treatment_i + \beta_5 \times diabetes_i \times treatment_i + \beta_6 \times ejf\_per_i \times treatment_i $ where the model is $ Y ~ Binomial (n_i, p_i) $</p>
<p>Our final model was fitted in the binomial distribution. The logit $ \mu_i $ is the log odds of death or hospitalization with heath failure.</p>
<p>The following betas are the dummy variable:</p>
<ul>
<li><p>beta 1 is 1 when patient has a history of diabetes</p></li>
<li><p>beta 2 is 1 when patient has a history of previous Dignoxin use</p></li>
<li><p>beta 4 is 1 when patient allowcated to Dignoxin treatment group.</p></li>
</ul>
<p>From our analysis, the variables that affect the probability of death or hospitalization with heath failure are: history of diabetes, dignoxin within past week, ejection rate and the treatment. We have ommited age and gender where the p-value showed insignificant relationship on the odds of death or hospitalisation with heart failure. The research question was interested in whether taking dignosin can change the rate of death or hospitalization due to heath failure. From our analysis, we found that there are interactions between the treatment with history of diabetes and treatment with ejection fraction.</p>
<p>At the average ejection fraction (28.64%):</p>
<ul>
<li><p>The patient that has diabetes history, the odds ratio of death or hospitalization with heath failure is 1.17 so the effect of treatment is similar between the two groups.</p></li>
<li><p>The patient with no history of diabetes, the odds ration of death or hospitalization with heart failure is 1.5 which means that the odds of death or hospitalization with heart failure is higher in the placebo group compares to the Dignoxin group.</p></li>
<li><p>Tthe odds ration of death or hospitalization with heart failure is estimated to be 1.01 - 1.83 more when the patient have diabetes history and treatment is dignoxin.</p></li>
</ul>
<p>When the patient has no diabetes history:</p>
<ul>
<li><p>The lower the ejection fraction, the odds ration of death or hospitalization with heart failure in both placebo and dignoxin but the placebo group has the higer odds than the dignoxin group.</p></li>
<li><p>As the ejection fraction increases, the odds also decreases</p></li>
<li><p>At the ejection fraction of 45%, the odds are almost the same in both treatment group but the placebo is slightly higher.</p></li>
</ul>
<p>When the patient has diabetes history:</p>
<ul>
<li><p>The lower the ejection fraction, the odds ration of death or hospitalization with heart failure in both placebo and dignoxin but the placebo group has the higer odds than the dignoxin group.</p></li>
<li><p>As the ejection fraction increases, the odds also decreases</p></li>
<li><p>However, as approximately 30% ejection fraction, the odds have become equivalent in both groups.</p></li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>